[versions]
agp = "8.11.1"
dokka = "2.1.0"
json = "1.9.0"
compose = "1.9.2"
kotlin = "2.2.10"
kotlinter = "5.2.0"
android-minSdk = "24"
android-compileSdk = "36"
vanniktech = "0.34.0"

[libraries]
json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "json" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
